# Supabase configuration file

[api]
enabled = true
port = 54331
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54332
shadow_port = 54330
major_version = 15

[realtime]
enabled = false

[studio]
enabled = true
port = 54333
api_url = "http://localhost:54331"

[inbucket]
enabled = true
port = 54334
smtp_port = 54335
pop3_port = 54336

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true

[auth.sms]
enable_signup = true
template = "Your code is {{ .Code }}"

[analytics]
enabled = false